[package]
name = "starknetbook_chapter_AA"
version = "0.1.0"

[scripts]
setup = "export STARKNET_NETWORK=alpha-goerli && export STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount"
declare = "starknet declare --contract target/release/starknetbook_chapter_7_HelloAccount.json --account vote_admin --max_fee 100000000000000000"
deploy = "starknet deploy --class_hash 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe --account vote_admin --max_fee 100000000000000000"

[dependencies]
starknet = "2.1.0-rc2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", branch = "cairo-2" }

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
